# Generated by Django 2.2.7 on 2019-12-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='', max_length=25, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='', max_length=512)),
                ('privilege_level', models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('TA', 'TA')], default='', max_length=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=25)),
                ('last_name', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.EmailField(blank=True, default='', max_length=25)),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('address', models.CharField(blank=True, default='', max_length=25)),
                ('qualifications', models.CharField(blank=True, default='No qualification entered by this TA yet!', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('lecture_num', models.CharField(default='', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sprint2.User')),
            ],
        ),
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sprint2.User')),
                ('pref_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_1', to='Sprint2.Course')),
                ('pref_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_2', to='Sprint2.Course')),
                ('pref_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_3', to='Sprint2.Course')),
                ('quals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qual', to='Sprint2.User')),
            ],
            bases=('Sprint2.user',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=3)),
                ('type', models.CharField(choices=[('LEC', 'LEC'), ('DIS', 'DIS'), ('LAB', 'LAB'), ('ONL', 'ONL')], default='', max_length=3)),
                ('days', models.CharField(default='', max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.Course')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sprint2.Ta')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.Section')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.Ta')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.Course')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.Ta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'lecture_num'), name='course_id'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='section_id'),
        ),
        migrations.AddConstraint(
            model_name='enroll',
            constraint=models.UniqueConstraint(fields=('ta', 'section'), name='enroll_identifier'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course', 'ta'), name='course_assignment_identifier'),
        ),
    ]
